In [0]:
import tensorflow as tf

In [5]:
# check version of the tensorflow
print(tf.__version__)

1.14.0


In [0]:
# Create tensorflow object called tensor
hello_constant = tf.constant('Hello world')

In [3]:
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
# Tensorflow Session()
with tf.Session() as sess:
  # Run the tf.constant operation in the session
  output = sess.run(hello_constant)
  print(output)

b'Hello world'


In [6]:
# another way to print
sess = tf.Session()
print(sess.run(hello_constant))
sess.close()

b'Hello world'


In [7]:
# Three type of data: constant, place holder, variable
# Multiply two constants
a = tf.constant(4.0)
b = tf.constant(6.0)
c = a * b
c

<tf.Tensor 'mul:0' shape=() dtype=float32>

In [8]:
sess = tf.Session()
print(sess.run(c))
sess.close()

24.0


In [9]:
a = tf.constant(4.0,tf.float32) # specify type of constant, f32 is the default
b = tf.constant(6.0)

sess = tf.Session()
print(sess.run([a,b]))
sess.close()

[4.0, 6.0]


In [13]:
# Place holders: promise to provide a value later

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

c =  a + b

sess = tf.Session()
print(sess.run(c,feed_dict={a:[1,2,3],b:[7,8,9]}))
#sess.close()

[ 8. 10. 12.]


In [15]:
# Do another calculation
d = c*10
print(sess.run(d,{a:[[1,2,3],[4,5,6]], 
                 b:[[10,11,12],[13,14,15]]}))
sess.close()

[[110. 130. 150.]
 [170. 190. 210.]]


In [18]:
# Variable: allow us to add trainable parameters to a graph
w = tf.Variable([0.5],tf.float32)
# need to run this code to initialize the Variables()
init = tf.global_variables_initializer() 

sess = tf.Session()
sess.run(init)
print(sess.run(w))

[0.5]


In [19]:
# y = b + w*x

w = tf.Variable([0.1],tf.float32)
b = tf.Variable([-0.5],tf.float32)
x = tf.placeholder(tf.float32)

y = w*x + b

init = tf.global_variables_initializer() 

sess = tf.Session()
sess.run(init)
print(sess.run(y,{x:[1,2,3,5,6,8]}))

[-0.4        -0.3        -0.19999999  0.          0.10000002  0.3       ]


In [30]:
# Math
a = tf.add(1,5)
b = tf.subtract(8,6)
c = tf.multiply(2,4)

sess = tf.Session()
print(sess.run([a,b,c]))
sess.close()

[6, 2, 8]


In [32]:
# Activation Functions
import numpy as np

# sigmoid
def sigmoid_(a):
  return 1/(1+np.exp(-a))

sigmoid_(0.5)

0.6224593312018546

In [33]:
# relu
def relu_(a):
  return np.maximum(0,a)

relu_([-2,5,-3])

array([0, 5, 0])

In [28]:
# softmax
def softmax(a):
  return np.exp(a)/np.sum(np.exp(a),axis=0)

print(softmax([2,4,5]))

[0.03511903 0.25949646 0.70538451]


In [35]:
# with tensorflow

a = [0.2,4,-5]

sigmoid_activation = tf.sigmoid(a)
tanh_activation = tf.tanh(a)
relu_activation = tf.nn.relu(a)

with tf.Session() as sess:
  b1 = sess.run(sigmoid_activation)
  b2 = sess.run(tanh_activation)
  b3 = sess.run(relu_activation)
  
  print('b1:',b1)
  print('b2:',b2)
  print('b3:',b3)

b1: [0.54983395 0.98201376 0.00669285]
b2: [ 0.19737528  0.9993292  -0.99990916]
b3: [0.2 4.  0. ]


In [39]:
# truncated_normal: Gaussian distrubuted with mean 0 and std 1
a = tf.truncated_normal([2,3])
sess = tf.Session()
sess.run(a)
#sess.close()

array([[ 0.8757731 , -0.26341593, -1.9293851 ],
       [ 0.7241138 , -0.9559266 , -0.5861528 ]], dtype=float32)

In [41]:
# loss function
w = tf.Variable([0.1],tf.float32)
b = tf.Variable([-0.5],tf.float32)

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

y_model = w*x + b

mse = tf.square(y_model - y)
loss = tf.reduce_sum(mse)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

print(sess.run(loss,{x:[1,2,3,4],y:[10,11,24,8]}))  # total lost
sess.close() 

887.1


In [43]:
# optimization
w = tf.Variable([0.1],tf.float32)
b = tf.Variable([-0.5],tf.float32)

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

y_model = w*x + b

mse = tf.square(y_model - y)
loss = tf.reduce_sum(mse)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for i in range(3):
  sess.run(loss,{x:[1,2,3,4],y:[10,11,24,8]})

print(sess.run([w,b]))

[array([0.1], dtype=float32), array([-0.5], dtype=float32)]


In [0]:
sess.close()

In [0]:
# neural network

# define and initialize hyper parameters
learning_rate = 0.1
training_epochs = 100

cost_history = np.empty(shape=[1],dtype=float)

In [0]:
n_dim = 4  #n_dim = X.shape[1]
n_class = 2

In [0]:
x = tf.placeholder(tf.float32,[None,n_dim])
w = tf.Variable(tf.zeros([n_dim,n_class]))
b = tf.Variable(tf.zeros([n_class]))

In [0]:
# initialize all variables
init = tf.global_variables_initializer()
#define cost function
y1 = tf.placeholder(tf.float32,[None,n_class]) # actual value
y = tf.nn.softmax(tf.matmul(x,w)+b)  # model value

cost_function = tf.reduce_mean(-tf.reduce_sum((y1*tf.log(y)),reduction_indices=[1]))
training_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)

In [0]:
# initialize the session
sess = tf.Session()
sess.run(init)

In [0]:
mse_history = []
# calculate the cost for each epoch
for epoch in range(training_epochs):
  sess.run(training_step,feed_dict={x:x_train,y1:y_train})
  cost = sess.run(cost_function,feed_dict={x:x_train,y1:y_train})
  cost_history = np.append(cost_history,cost)
  y_pred = sess.run(y,feed_dict={x:x_test})
  print('epoch:',epoch,'-','cost:',cost)
  
  mse = tf.reduce_mean(tf.square(y_pred - y_test))
  mse_history.append(sess.run(mse))
 
# print the final mse
print('MSE:', mse_history)
#plt.plot(mse_history,'ro-')

In [0]:
correct_prediction = tf.equal(tf.argmax(y,1),tf.argmax(y1,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
print('Accuracy:',(sess.run(accuracy,feed_dict={x:x_test, y1:y_test})))

In [0]:
plt.plot(range(len(cost_history)),cost_history)
plt.axis([0,training_epochs,0,np.max(cost_history)])
